import {
  AcademicCapIcon,
  AdjustmentsHorizontalIcon,
  ArrowDownTrayIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowUpTrayIcon,
  ArrowTrendingUpIcon,
  Bars3Icon,
  BellIcon,
  BookmarkIcon,
  BookmarkSquareIcon,
  BuildingLibraryIcon,
  CalendarDaysIcon,
  ChartPieIcon,
  ChatBubbleLeftRightIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  Cog6ToothIcon,
  CpuChipIcon,
  DocumentChartBarIcon,
  EnvelopeOpenIcon,
  FolderIcon,
  GlobeAltIcon,
  HandRaisedIcon,
  HeartIcon,
  HomeIcon,
  MagnifyingGlassIcon,
  LightBulbIcon,
  LinkIcon,
  MapPinIcon,
  PaintBrushIcon,
  PaperAirplaneIcon,
  PhotoIcon,
  PlusIcon,
  PuzzlePieceIcon,
  RocketLaunchIcon,
  SignalIcon,
  SunIcon,
  MoonIcon,
  SparklesIcon,
  Squares2X2Icon,
  UserCircleIcon,
  UserGroupIcon,
  UserPlusIcon,
  UsersIcon,
  WrenchScrewdriverIcon,
  XMarkIcon
} from '@heroicons/react/24/outline'
import {
  BookmarkIcon as BookmarkSolidIcon,
  HeartIcon as HeartSolidIcon,
  StarIcon as StarSolidIcon
} from '@heroicons/react/24/solid'

const ICONS = {
  home: HomeIcon,
  studentCollab: UserGroupIcon,
  collaboration: HandRaisedIcon,
  colleges: BuildingLibraryIcon,
  createPost: PlusIcon,
  saved: BookmarkIcon,
  savedSolid: BookmarkSolidIcon,
  savedSquare: BookmarkSquareIcon,
  notification: BellIcon,
  profile: UserCircleIcon,
  menu: Bars3Icon,
  settings: Cog6ToothIcon,
  smartSuggestions: SparklesIcon,
  follow: UserPlusIcon,
  collabRequests: HandRaisedIcon,
  posts: Squares2X2Icon,
  stats: ChartPieIcon,
  teams: PuzzlePieceIcon,
  schedule: CalendarDaysIcon,
  category: Squares2X2Icon,
  organization: BuildingLibraryIcon,
  organizer: UsersIcon,
  website: GlobeAltIcon,
  globe: GlobeAltIcon,
  duration: CalendarDaysIcon,
  calendar: CalendarDaysIcon,
  link: LinkIcon,
  like: HeartIcon,
  likeSolid: HeartSolidIcon,
  comment: ChatBubbleLeftRightIcon,
  share: ArrowPathIcon,
  followCheck: UserGroupIcon,
  save: BookmarkIcon,
  saveSolid: BookmarkSolidIcon,
  plus: PlusIcon,
  roleStudent: AcademicCapIcon,
  roleCollege: BuildingLibraryIcon,
  roleRepresentative: UserGroupIcon,
  uploadPhoto: PhotoIcon,
  uploadLogo: ArrowUpTrayIcon,
  upload: ArrowUpTrayIcon,
  highlight: SparklesIcon,
  explore: RocketLaunchIcon,
  arrowRight: ArrowRightIcon,
  edit: WrenchScrewdriverIcon,
  shareProfile: ArrowUpTrayIcon,
  badge: StarSolidIcon,
  modalClose: XMarkIcon,
  aiAssistant: CpuChipIcon,
  scrollTop: ArrowUpIcon,
  chevronDown: ChevronDownIcon,
  marker: MapPinIcon,
  dept: AcademicCapIcon,
  external: ArrowUpTrayIcon,
  send: PaperAirplaneIcon,
  filter: AdjustmentsHorizontalIcon,
  camera: PhotoIcon,
  folder: FolderIcon,
  rocket: RocketLaunchIcon,
  sparkles: SparklesIcon,
  signal: SignalIcon,
  sun: SunIcon,
  moon: MoonIcon,
  mail: EnvelopeOpenIcon,
  idea: LightBulbIcon,
  document: DocumentChartBarIcon,
  search: MagnifyingGlassIcon,
  creative: PaintBrushIcon,
  growth: ArrowTrendingUpIcon
}

const FALLBACK_ICON = SparklesIcon

const Icon = ({ name, className, ...props }) => {
  const IconComponent = ICONS[name] || FALLBACK_ICON
  return <IconComponent className={className} aria-hidden="true" {...props} />
}

export default Icon
export { ICONS }
